---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(Rlab)
```

```{r}
#setting up variables

S <-  c(5000000)
I <-  c(20)
R <-  c(0)

N = S[1] + I[1] + R[1]

Pspread <-  0.4
Pcontact <-  0.6
Precover <-  0.1
```

```{r}

#Basic Model
#if You're infected you're more likely to stay home
#if you're not infected you go around as bout
#
#
steps = 5000

for( i in 2:steps){

  S <- c(S, S[i-1] - (Pcontact * Pspread * I[i-1]/N * S[i-1]))
  I <- c(I, I[i-1] + (Pcontact * Pspread * I[i-1]/N * S[i-1]) - (Precover * I[i-1]))
  R <- c(R, R[i-1] + Precover * I[i-1])
  
  
}

data <- data.frame(S,I,R) %>% mutate(step = 1:n())
data
```

```{r}
data %>% ggplot(aes(x = step)) + geom_line(aes(y = S, color = "green")) + geom_line(aes(y = I, color = "yellow")) + geom_line(aes(y = R, color = "red")) + xlim(0,200)
```




```{r}
#Stepwise Model

#init population and probabilities
S <-  50000
I <-  20
R <-  0

N = S + I + R

Pspread <-  0.4
Pcontact <-  0.6
Precover <-  0.1

#sets up the matrix 
mod <- matrix(NA, nrow = N, ncol = 3)
colnames(mod) <- c("Step","Isolation", "Isolation Counter")

#Step: S = 1, I = 2, R = 3
#Isolate: 1 = True, 0 = False

#sets up SIR
mod[1:S,1] <- 1
mod[(S+1):(S+I), 1] <- 2
if(S + I + 1 <= S + I + R){
  mod[(S + I + 1):(S + I + R),1] <- 3
  
}

#sets up isolation
# 0.05 of S isolate
# 0.1 of I isolate
mod[mod[,"Step"] == 1,"Isolation"] <- rbern(nrow(mod[mod[,"Step"] == 1,]), 0.01)
mod[mod[,"Step"] == 2,"Isolation"] <- rbern(nrow(mod[mod[,"Step"] == 2,]), 0.1)
mod[mod[,"Step"] == 3,"Isolation"] <- 0

mod[,"Isolation Counter"] <- 0

head(mod)

#sets up data frame
SIRdf <- data.frame("Step" = 0, "S" = S, "I" = I, "R" = I)


```



```{r}
#transitions
steps = 500


for(i in 1:steps){
  
  #increase the day count for Isolation Counter + leaves isolation after 14 days
  mod[mod[,"Isolation"] == 1, "Isolation Counter"] = mod[mod[,"Isolation"] == 1, "Isolation Counter"] + 1
  mod[mod[,"Isolation Counter"] >= 14, "Isolation"] = 0
  mod[mod[,"Isolation Counter"] >= 14, "Isolation Counter"] = 0
  
  # S to I
  
  #sets up the transition from S to I  
  # The to meet is sum(infected not isolated)/sum(not isolating)
  # Look at People that are not isolating and calculating what the probability of them meeting is
  Pmeet <- length(mod[(mod[,"Step"] == 2 & mod[,"Isolation"] == 0 ) , "Step"])/N
  transition <- rbern(length(mod[(mod[,"Step"] == 1 & mod[,"Isolation"] == 0 ) , "Step"]), Pcontact * Pspread * Pmeet)
  
  
  
  #infected goes into isolation at a set prob Piso.S
  iso.transition <- as.matrix(transition)
  Piso.S <- 0.1
  
  iso.transition[iso.transition[,1] == 1,] <- rbern(length(iso.transition[iso.transition[,1] == 1,]), Piso.S)
  
  
  #updater function sends to iso then updates
  newI <- mod[(mod[,"Step"] == 1 & mod[,"Isolation"] == 0 ) , "Step"]  +  transition
  mod[(mod[,"Step"] == 1 & mod[,"Isolation"] == 0 ) , c("Step", "Isolation")] <- cbind(newI,iso.transition)
  
  
  # I to R
  # this is a stationary probability
  
  mod[mod[,"Step"] == 2, "Step"] <- mod[mod[,"Step"] == 2, "Step"]  +  
    rbern(length(mod[mod[,"Step"] == 2, "Step"]), Precover)
  
  
  # New S goes into isolation
  
  
  #updates data frame
  newS <- sum(mod[,"Step"] == 1)
  newI <- sum(mod[,"Step"] == 2)
  newR <- sum(mod[,"Step"] == 3)
  SIRdf <- rbind(SIRdf,c(i,newS,newI,newR))
  
}

SIRdf
```

```{r}
SIRdf %>% ggplot(aes(x = Step)) + geom_line(aes(y = S, colour = "Suseptible")) + geom_line(aes(y = I, colour = "Infected")) + geom_line(aes(y = R, colour = "Recovered")) + xlim(0,250)
```


```{r}

## Testing out prisoner's dilemma
actions <- c("isolate", "go outside")

risk <- function(action){
  if(action == actions[1]){
    return(0);
  }
  else if(action == actions[2]){
    return(2)
  }
}

utility <- function(x, action){
  return(x)
}

#each person has a gaussian min utility
#calculate the risk


```



